export const RoundManagerABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", type: "address", internalType: "address" },
      { name: "_vault", type: "address", internalType: "address" },
      {
        name: "_config",
        type: "tuple",
        internalType: "struct RoundManager.RoundConfig",
        components: [
          {
            name: "targetRaise",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "equityPercentage",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sharePrice",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "deadline", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "_companySymbol",
        type: "string",
        internalType: "string",
      },
      { name: "_founder", type: "address", internalType: "address" },
      {
        name: "_fndrIdentity",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BASIS_POINTS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FOUNDER_YIELD_SHARE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_WITHDRAWAL_RATE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PLATFORM_SUCCESS_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SECONDS_PER_MONTH",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "canFounderWithdraw",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "bool", internalType: "bool" },
      { name: "", type: "string", internalType: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canFounderWithdrawView",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "bool", internalType: "bool" },
      { name: "", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimYield",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "config",
    inputs: [],
    outputs: [
      { name: "targetRaise", type: "uint256", internalType: "uint256" },
      {
        name: "equityPercentage",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "sharePrice", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "founderWithdraw",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "founderYieldClaimed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEquityToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFounder",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInvestorInfo",
    inputs: [{ name: "investor", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "contribution",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "equityTokens",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "yieldBalance",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "yieldClaimed", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getInvestorInfoView",
    inputs: [{ name: "investor", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "contribution",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "equityTokens",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "yieldBalance",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "yieldClaimed", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundInfo",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoundManager.RoundState",
      },
      { name: "totalRaised", type: "uint256", internalType: "uint256" },
      {
        name: "totalWithdrawn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensIssued",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "investorCount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "vaultBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRoundInfoView",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoundManager.RoundState",
      },
      { name: "totalRaised", type: "uint256", internalType: "uint256" },
      {
        name: "totalWithdrawn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensIssued",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "investorCount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "vaultBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getYieldInfo",
    inputs: [],
    outputs: [
      {
        name: "totalVaultBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalYieldAccrued",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "currentAPY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getYieldInfoView",
    inputs: [],
    outputs: [
      {
        name: "totalVaultBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalYieldAccrued",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "currentAPY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "invest",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "investorYieldBalance",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "investorYieldClaimed",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastYieldUpdate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "platformWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "round",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoundManager.RoundState",
      },
      { name: "founder", type: "address", internalType: "address" },
      {
        name: "equityToken",
        type: "address",
        internalType: "contract StartupEquityToken",
      },
      { name: "totalRaised", type: "uint256", internalType: "uint256" },
      {
        name: "totalWithdrawn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lastWithdrawal",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensIssued",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "completionTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalYieldDistributed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateYield",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vault",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract MockVault" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "FounderWithdrawal",
    inputs: [
      {
        name: "founder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "principalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "yieldAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvestmentMade",
    inputs: [
      {
        name: "investor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "usdcAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokensReceived",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalRaised",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvestorYieldClaimed",
    inputs: [
      {
        name: "investor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlatformFeeCollected",
    inputs: [
      {
        name: "platformWallet",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "feeAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalRaised",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundCompleted",
    inputs: [
      {
        name: "totalRaised",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "completionTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "completionReason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundCreated",
    inputs: [
      {
        name: "founder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "equityToken",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "companyName",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "targetRaise",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "equityPercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "YieldDistributed",
    inputs: [
      {
        name: "totalYield",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "founderYield",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "investorYield",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "ExceedsMonthlyWithdrawalLimit", inputs: [] },
  { type: "error", name: "InsufficientFunds", inputs: [] },
  { type: "error", name: "InsufficientVaultBalance", inputs: [] },
  { type: "error", name: "InvalidCompanyName", inputs: [] },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "InvalidEquityPercentage", inputs: [] },
  { type: "error", name: "InvalidFndrIdentity", inputs: [] },
  { type: "error", name: "InvalidFndrIdentityAddress", inputs: [] },
  { type: "error", name: "InvalidFounderAddress", inputs: [] },
  {
    type: "error",
    name: "InvalidOperation",
    inputs: [{ name: "reason", type: "string", internalType: "string" }],
  },
  { type: "error", name: "InvalidPlatformWalletAddress", inputs: [] },
  { type: "error", name: "InvalidRoundConfig", inputs: [] },
  { type: "error", name: "InvalidRoundState", inputs: [] },
  { type: "error", name: "InvalidSharePrice", inputs: [] },
  { type: "error", name: "InvalidTargetRaise", inputs: [] },
  { type: "error", name: "InvalidUSDCAddress", inputs: [] },
  { type: "error", name: "InvalidVaultAddress", inputs: [] },
  { type: "error", name: "InvestmentExceedsTargetRaise", inputs: [] },
  { type: "error", name: "InvestmentTooSmall", inputs: [] },
  {
    type: "error",
    name: "MultipleWithdrawalsWithinMonthExceedLimit",
    inputs: [],
  },
  { type: "error", name: "OnlyFounderCanCall", inputs: [] },
  { type: "error", name: "RoundDeadlinePassed", inputs: [] },
  { type: "error", name: "RoundNotCompleted", inputs: [] },
  { type: "error", name: "RoundNotInFundraisingState", inputs: [] },
  { type: "error", name: "USDCTransferFailed", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  {
    type: "error",
    name: "WithdrawalAmountMustBeGreaterThanZero",
    inputs: [],
  },
] as const;
