export const RoundFactoryABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", type: "address", internalType: "address" },
      {
        name: "_sharedYieldVault",
        type: "address",
        internalType: "address",
      },
      {
        name: "_fndrIdentity",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ROUND_CREATION_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createRound",
    inputs: [
      { name: "targetRaise", type: "uint256", internalType: "uint256" },
      {
        name: "equityPercentage",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "sharePrice", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "companySymbol", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "founderToRound",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllRounds",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundByFounder",
    inputs: [{ name: "founder", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalRoundsCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "identity",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract FndrIdentity",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isActiveRound",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markRoundInactive",
    inputs: [
      { name: "roundAddress", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "platformWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rounds",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sharedYieldVault",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract MockVault" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "RoundDeployed",
    inputs: [
      {
        name: "roundAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "founder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "targetRaise",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "FeeFailed", inputs: [] },
  { type: "error", name: "InvalidParams", inputs: [] },
  { type: "error", name: "NotVerifiedFounder", inputs: [] },
  { type: "error", name: "RoundExists", inputs: [] },
] as const;
