import { defineChain } from 'viem';

// Mantle Sepolia Chain Configuration
export const mantleSepolia = defineChain({
  id: 5003,
  name: 'Mantle Sepolia',
  nativeCurrency: { name: 'MNT', symbol: 'MNT', decimals: 18 },
  rpcUrls: {
    default: { http: ['https://rpc.sepolia.mantle.xyz'] },
  },
  blockExplorers: {
    default: { name: 'Mantle Explorer', url: 'https://sepolia.mantlescan.xyz' },
  },
  testnet: true,
});

// Contract Addresses on Mantle Sepolia
export const CONTRACTS = {
  MockUSDC: '0xFFCEaa5F520c3b40d4A5A81422Aa6Ed32C978d81',
  MockVault: '0x0a4010b637f77bA89B89b6d182b114242bBe78B1',
  FndrIdentity: '0x88A684C010B9286bd0b0c71738Df673c4A733fF3',
  RoundFactory: '0x456967939D5b14Ee0dEe8C7c05b1424132d5DDC8',
  StartupSecondaryMarket: '0x24F62664f2055DC220156D4d263fd5590Af96e53',
} as const;

// ABIs

export const FndrIdentityABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "getUniqueIdentifier",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserRole",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum FndrIdentity.UserRole" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isFounder",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isInvestor",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isUserRegistered",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isVerifiedUser",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isZKPassportVerified",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerUserRole",
    inputs: [{ name: "role", type: "uint8", internalType: "enum FndrIdentity.UserRole" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "registerZKPassportUser",
    inputs: [{ name: "uniqueIdentifier", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usedIdentifiers",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userRoles",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint8", internalType: "enum FndrIdentity.UserRole" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "zkPassportIdentifiers",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "UserRoleRegistered",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "role", type: "uint8", indexed: false, internalType: "enum FndrIdentity.UserRole" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ZKPassportVerified",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      { name: "nullifierHash", type: "bytes32", indexed: false, internalType: "bytes32" },
    ],
    anonymous: false,
  },
  { type: "error", name: "IdentifierAlreadyUsed", inputs: [] },
  { type: "error", name: "InvalidIdentifier", inputs: [] },
  { type: "error", name: "InvalidRole", inputs: [] },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "UserAlreadyRegistered", inputs: [] },
  { type: "error", name: "UserNotVerified", inputs: [] },
] as const;

export const RoundFactoryABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", type: "address", internalType: "address" },
      {
        name: "_sharedYieldVault",
        type: "address",
        internalType: "address",
      },
      {
        name: "_fndrIdentity",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ROUND_CREATION_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createRound",
    inputs: [
      { name: "targetRaise", type: "uint256", internalType: "uint256" },
      {
        name: "equityPercentage",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "sharePrice", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "companySymbol", type: "string", internalType: "string" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "founderToRound",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllRounds",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundByFounder",
    inputs: [{ name: "founder", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalRoundsCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "identity",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract FndrIdentity",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isActiveRound",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markRoundInactive",
    inputs: [
      { name: "roundAddress", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "platformWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rounds",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sharedYieldVault",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract MockVault" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "RoundDeployed",
    inputs: [
      {
        name: "roundAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "founder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "targetRaise",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "FeeFailed", inputs: [] },
  { type: "error", name: "InvalidParams", inputs: [] },
  { type: "error", name: "NotVerifiedFounder", inputs: [] },
  { type: "error", name: "RoundExists", inputs: [] },
] as const;

export const RoundManagerABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", type: "address", internalType: "address" },
      { name: "_vault", type: "address", internalType: "address" },
      {
        name: "_config",
        type: "tuple",
        internalType: "struct RoundManager.RoundConfig",
        components: [
          {
            name: "targetRaise",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "equityPercentage",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "sharePrice",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "deadline", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "_companySymbol",
        type: "string",
        internalType: "string",
      },
      { name: "_founder", type: "address", internalType: "address" },
      {
        name: "_fndrIdentity",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BASIS_POINTS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "FOUNDER_YIELD_SHARE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_WITHDRAWAL_RATE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "PLATFORM_SUCCESS_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "SECONDS_PER_MONTH",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "canFounderWithdraw",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "bool", internalType: "bool" },
      { name: "", type: "string", internalType: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canFounderWithdrawView",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "", type: "bool", internalType: "bool" },
      { name: "", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimYield",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "config",
    inputs: [],
    outputs: [
      { name: "targetRaise", type: "uint256", internalType: "uint256" },
      {
        name: "equityPercentage",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "sharePrice", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "founderWithdraw",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "founderYieldClaimed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEquityToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFounder",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInvestorInfo",
    inputs: [{ name: "investor", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "contribution",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "equityTokens",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "yieldBalance",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "yieldClaimed", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getInvestorInfoView",
    inputs: [{ name: "investor", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "contribution",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "equityTokens",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "yieldBalance",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "yieldClaimed", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRoundInfo",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoundManager.RoundState",
      },
      { name: "totalRaised", type: "uint256", internalType: "uint256" },
      {
        name: "totalWithdrawn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensIssued",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "investorCount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "vaultBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRoundInfoView",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoundManager.RoundState",
      },
      { name: "totalRaised", type: "uint256", internalType: "uint256" },
      {
        name: "totalWithdrawn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensIssued",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "investorCount",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "vaultBalance", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getYieldInfo",
    inputs: [],
    outputs: [
      {
        name: "totalVaultBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalYieldAccrued",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "currentAPY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getYieldInfoView",
    inputs: [],
    outputs: [
      {
        name: "totalVaultBalance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalYieldAccrued",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "currentAPY", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "invest",
    inputs: [{ name: "usdcAmount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "investorYieldBalance",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "investorYieldClaimed",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastYieldUpdate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "platformWallet",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "round",
    inputs: [],
    outputs: [
      {
        name: "state",
        type: "uint8",
        internalType: "enum RoundManager.RoundState",
      },
      { name: "founder", type: "address", internalType: "address" },
      {
        name: "equityToken",
        type: "address",
        internalType: "contract StartupEquityToken",
      },
      { name: "totalRaised", type: "uint256", internalType: "uint256" },
      {
        name: "totalWithdrawn",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "lastWithdrawal",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "tokensIssued",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "completionTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalYieldDistributed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateYield",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vault",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract MockVault" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "FounderWithdrawal",
    inputs: [
      {
        name: "founder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "principalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "yieldAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvestmentMade",
    inputs: [
      {
        name: "investor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "usdcAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "tokensReceived",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalRaised",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvestorYieldClaimed",
    inputs: [
      {
        name: "investor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlatformFeeCollected",
    inputs: [
      {
        name: "platformWallet",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "feeAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "totalRaised",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundCompleted",
    inputs: [
      {
        name: "totalRaised",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "completionTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "completionReason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundCreated",
    inputs: [
      {
        name: "founder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "equityToken",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "companyName",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "targetRaise",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "equityPercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "YieldDistributed",
    inputs: [
      {
        name: "totalYield",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "founderYield",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "investorYield",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "ExceedsMonthlyWithdrawalLimit", inputs: [] },
  { type: "error", name: "InsufficientFunds", inputs: [] },
  { type: "error", name: "InsufficientVaultBalance", inputs: [] },
  { type: "error", name: "InvalidCompanyName", inputs: [] },
  { type: "error", name: "InvalidDeadline", inputs: [] },
  { type: "error", name: "InvalidEquityPercentage", inputs: [] },
  { type: "error", name: "InvalidFndrIdentity", inputs: [] },
  { type: "error", name: "InvalidFndrIdentityAddress", inputs: [] },
  { type: "error", name: "InvalidFounderAddress", inputs: [] },
  {
    type: "error",
    name: "InvalidOperation",
    inputs: [{ name: "reason", type: "string", internalType: "string" }],
  },
  { type: "error", name: "InvalidPlatformWalletAddress", inputs: [] },
  { type: "error", name: "InvalidRoundConfig", inputs: [] },
  { type: "error", name: "InvalidRoundState", inputs: [] },
  { type: "error", name: "InvalidSharePrice", inputs: [] },
  { type: "error", name: "InvalidTargetRaise", inputs: [] },
  { type: "error", name: "InvalidUSDCAddress", inputs: [] },
  { type: "error", name: "InvalidVaultAddress", inputs: [] },
  { type: "error", name: "InvestmentExceedsTargetRaise", inputs: [] },
  { type: "error", name: "InvestmentTooSmall", inputs: [] },
  {
    type: "error",
    name: "MultipleWithdrawalsWithinMonthExceedLimit",
    inputs: [],
  },
  { type: "error", name: "OnlyFounderCanCall", inputs: [] },
  { type: "error", name: "RoundDeadlinePassed", inputs: [] },
  { type: "error", name: "RoundNotCompleted", inputs: [] },
  { type: "error", name: "RoundNotInFundraisingState", inputs: [] },
  { type: "error", name: "USDCTransferFailed", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  {
    type: "error",
    name: "WithdrawalAmountMustBeGreaterThanZero",
    inputs: [],
  },
] as const;

export const StartupEquityTokenABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_symbol", type: "string", internalType: "string" },
      { name: "_companyName", type: "string", internalType: "string" },
      { name: "_equityPercentage", type: "uint256", internalType: "uint256" },
      { name: "_founder", type: "address", internalType: "address" },
      { name: "_campaign", type: "address", internalType: "address" },
      { name: "_fndrIdentity", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "DEFAULT_PARTITION",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "companyName",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "equityPercentage",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "founder",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenInfo",
    inputs: [],
    outputs: [
      { name: "tokenName", type: "string", internalType: "string" },
      { name: "tokenSymbol", type: "string", internalType: "string" },
      { name: "company", type: "string", internalType: "string" },
      { name: "equity", type: "uint256", internalType: "uint256" },
      { name: "supply", type: "uint256", internalType: "uint256" },
      { name: "tokenFounder", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transfersEnabled",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "spender", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;

export const StartupSecondaryMarketABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_fndrIdentity", type: "address", internalType: "address" },
      { name: "_usdc", type: "address", internalType: "address" },
      { name: "_platformWallet", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MARKET_FEE_BPS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_ORDER_DURATION",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_HOLDING_PERIOD",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyTokens",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canSellTokens",
    inputs: [
      { name: "seller", type: "address", internalType: "address" },
      { name: "tokenContract", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "canSell", type: "bool", internalType: "bool" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelSellOrder",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createSellOrder",
    inputs: [
      { name: "tokenContract", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "pricePerToken", type: "uint256", internalType: "uint256" },
      { name: "durationHours", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getActiveOrdersForToken",
    inputs: [{ name: "tokenContract", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "activeOrders",
        type: "tuple[]",
        internalType: "struct StartupSecondaryMarket.SellOrder[]",
        components: [
          { name: "orderId", type: "uint256", internalType: "uint256" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "tokenContract", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "originalAmount", type: "uint256", internalType: "uint256" },
          { name: "pricePerToken", type: "uint256", internalType: "uint256" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "expiryTime", type: "uint256", internalType: "uint256" },
          { name: "active", type: "bool", internalType: "bool" },
          { name: "partition", type: "bytes32", internalType: "bytes32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMarketSummary",
    inputs: [{ name: "tokenContract", type: "address", internalType: "address" }],
    outputs: [
      { name: "totalActiveOrders", type: "uint256", internalType: "uint256" },
      { name: "totalVolume", type: "uint256", internalType: "uint256" },
      { name: "lowestPrice", type: "uint256", internalType: "uint256" },
      { name: "highestPrice", type: "uint256", internalType: "uint256" },
      { name: "lastPrice", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellerOrders",
    inputs: [{ name: "seller", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orders",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "tokenContract", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "originalAmount", type: "uint256", internalType: "uint256" },
      { name: "pricePerToken", type: "uint256", internalType: "uint256" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "expiryTime", type: "uint256", internalType: "uint256" },
      { name: "active", type: "bool", internalType: "bool" },
      { name: "partition", type: "bytes32", internalType: "bytes32" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "tokenContract", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "pricePerToken", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "expiryTime", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderExecuted",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "buyer", type: "address", indexed: true, internalType: "address" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "pricePerToken", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "totalPrice", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "platformFee", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderCancelled",
    inputs: [
      { name: "orderId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "seller", type: "address", indexed: true, internalType: "address" },
      { name: "amountReturned", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;

export const MockVaultABI = [
  {
    type: "constructor",
    inputs: [
      { name: "assetAddress", type: "address", internalType: "address" },
      { name: "_name", type: "string", internalType: "string" },
      { name: "_symbol", type: "string", internalType: "string" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "ANNUAL_YIELD_RATE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "asset",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToAssets",
    inputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToShares",
    inputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "assets", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCurrentAPY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "totalAssets",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "assets", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
      { name: "owner", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
] as const;

export const MockUSDCABI = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "airdrop",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "airdropCustom",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimedAirdrop",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "spender", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
] as const;

// User Role Enum (matches contract: enum UserRole { None, Founder, Investor })
export enum UserRole {
  None = 0,
  Founder = 1,
  Investor = 2,
}

// Round State Enum (matches contract)
export enum RoundState {
  Fundraising = 0,
  Completed = 1,
  Cancelled = 2,
}
